services:
  - type: web
    name: eaagads-asset-tracker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn eaagads.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eaagads.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        value: your-very-secret-key
      - key: ALLOWED_HOSTS
        value: eaagads-asset-tracker.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
